/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.baidu.carlifevehicle;

public final class R {
    public static final class anim {
        public static final int progress_round=0x7f040000;
        public static final int progress_small_round=0x7f040001;
        public static final int push_left_in=0x7f040002;
        public static final int push_left_out=0x7f040003;
        public static final int push_right_in=0x7f040004;
        public static final int push_right_out=0x7f040005;
    }
    public static final class array {
        public static final int carlife_setting_name=0x7f060000;
    }
    public static final class attr {
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int max=0x7f010005;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int roundColor=0x7f010000;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int roundProgressColor=0x7f010001;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int roundWidth=0x7f010002;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>STROKE</code></td><td>0</td><td></td></tr>
<tr><td><code>FILL</code></td><td>1</td><td></td></tr>
</table>
         */
        public static final int style=0x7f010007;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textColor=0x7f010003;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textIsDisplayable=0x7f010006;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textSize=0x7f010004;
    }
    public static final class color {
        public static final int bg_blue=0x7f0a0000;
        public static final int cl_bg_c_main=0x7f0a0001;
        public static final int cl_bg_e_dialog=0x7f0a0002;
        public static final int cl_btn_b=0x7f0a0003;
        public static final int cl_btn_c=0x7f0a0004;
        public static final int cl_btn_d=0x7f0a0005;
        public static final int cl_line_a1_item=0x7f0a0006;
        public static final int cl_line_a4=0x7f0a0007;
        public static final int cl_line_b_leftbar=0x7f0a0008;
        public static final int cl_line_c=0x7f0a0009;
        public static final int cl_line_d_dialog=0x7f0a000a;
        public static final int cl_other_c_highlight=0x7f0a000b;
        public static final int cl_press_b=0x7f0a000c;
        public static final int cl_press_c=0x7f0a000d;
        public static final int cl_press_d=0x7f0a000e;
        public static final int cl_press_e_dialog=0x7f0a000f;
        public static final int cl_text_a0_title=0x7f0a0010;
        public static final int cl_text_a2_content=0x7f0a0011;
        public static final int cl_text_a4_bgtext=0x7f0a0012;
        public static final int cl_text_a4_title=0x7f0a0013;
        public static final int cl_text_a5_content=0x7f0a0014;
        public static final int cl_text_a5_title=0x7f0a0015;
        public static final int cl_text_b_dialog=0x7f0a0016;
        public static final int cl_text_c_btn_dialog=0x7f0a0017;
        public static final int com_titlebar_bg=0x7f0a0018;
        public static final int com_titlebar_bg_night=0x7f0a0019;
        public static final int com_titlebar_middle_text=0x7f0a001a;
        public static final int com_titlebar_middle_text_night=0x7f0a001b;
        public static final int common_black=0x7f0a001c;
        public static final int common_list_main_text_color=0x7f0a001d;
        public static final int common_list_second_text_color=0x7f0a001e;
        public static final int common_title_color_title=0x7f0a001f;
        public static final int cp_bt_bg=0x7f0a0020;
        public static final int cp_click_c=0x7f0a0021;
        public static final int cp_click_e=0x7f0a0022;
        public static final int cp_cont_a=0x7f0a0023;
        public static final int cp_cont_b=0x7f0a0024;
        public static final int cp_cont_bg=0x7f0a0025;
        public static final int cp_cont_c=0x7f0a0026;
        public static final int cp_cont_d=0x7f0a0027;
        public static final int cp_cont_e=0x7f0a0028;
        public static final int cp_cont_f=0x7f0a0029;
        public static final int cp_cont_g=0x7f0a002a;
        public static final int cp_cont_h=0x7f0a002b;
        public static final int cp_cont_i=0x7f0a002c;
        public static final int cp_cont_m=0x7f0a002d;
        public static final int cp_cont_n=0x7f0a002e;
        public static final int cp_cont_u=0x7f0a002f;
        public static final int cp_label_bg=0x7f0a0030;
        public static final int cp_line_a=0x7f0a0031;
        public static final int cp_line_b=0x7f0a0032;
        public static final int cp_line_c=0x7f0a0033;
        public static final int cp_line_d=0x7f0a0034;
        public static final int cp_line_e=0x7f0a0035;
        public static final int cp_line_f=0x7f0a0036;
        public static final int cp_line_g=0x7f0a0037;
        public static final int cp_normal_bg=0x7f0a0038;
        public static final int cp_other_a=0x7f0a0039;
        public static final int cp_other_b=0x7f0a003a;
        public static final int cp_other_c=0x7f0a003b;
        public static final int cp_other_d=0x7f0a003c;
        public static final int cp_press_a=0x7f0a003d;
        public static final int cp_press_b=0x7f0a003e;
        public static final int cp_press_e=0x7f0a003f;
        public static final int cp_tab_bg=0x7f0a0040;
        public static final int frag_default_background_color=0x7f0a0041;
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f080000;
        public static final int activity_vertical_margin=0x7f080001;
        public static final int btn_retry_height=0x7f080002;
        public static final int btn_retry_width=0x7f080003;
        public static final int common_dialog_line=0x7f080017;
        public static final int common_icon_small=0x7f080018;
        public static final int common_item_height=0x7f080019;
        public static final int common_title_bar_height=0x7f08001a;
        public static final int connect_status_height=0x7f080004;
        public static final int font_size_background=0x7f080005;
        public static final int font_size_connect_status=0x7f080006;
        public static final int font_size_rate=0x7f080007;
        public static final int font_size_retry=0x7f080008;
        public static final int icon_connect_height=0x7f080009;
        public static final int icon_connect_width=0x7f08000a;
        public static final int menu_bottom_padding=0x7f08000b;
        public static final int menu_left_padding=0x7f08000c;
        public static final int menu_right_padding=0x7f08000d;
        public static final int menu_top_padding=0x7f08000e;
        public static final int phone_btn_layout_height=0x7f08000f;
        public static final int phone_btn_layout_width=0x7f080010;
        public static final int phone_btn_top=0x7f080011;
        public static final int phone_btn_width=0x7f080012;
        public static final int phone_btn_width1=0x7f080013;
        public static final int phone_desc=0x7f080014;
        public static final int phone_name=0x7f080015;
        public static final int title_bar_height=0x7f080016;
    }
    public static final class drawable {
        public static final int btn_new_user_guide=0x7f020000;
        public static final int btn_new_user_guide_press=0x7f020001;
        public static final int cailife_logo=0x7f020002;
        public static final int car_ic_calling=0x7f020003;
        public static final int car_ic_click=0x7f020004;
        public static final int car_ic_connect_error=0x7f020005;
        public static final int car_ic_exit=0x7f020006;
        public static final int car_ic_help=0x7f020007;
        public static final int car_ic_help_android_carlife01=0x7f020008;
        public static final int car_ic_help_android_carlife02=0x7f020009;
        public static final int car_ic_help_android_carlife03=0x7f02000a;
        public static final int car_ic_help_android_developer01=0x7f02000b;
        public static final int car_ic_help_android_developer02=0x7f02000c;
        public static final int car_ic_help_android_developer03=0x7f02000d;
        public static final int car_ic_help_android_usb01=0x7f02000e;
        public static final int car_ic_help_android_usb02=0x7f02000f;
        public static final int car_ic_help_android_usb03=0x7f020010;
        public static final int car_ic_help_android_usb04=0x7f020011;
        public static final int car_ic_help_aoa_ios=0x7f020012;
        public static final int car_ic_help_arrow=0x7f020013;
        public static final int car_ic_help_ios_wifi01=0x7f020014;
        public static final int car_ic_help_ios_wifi02=0x7f020015;
        public static final int car_ic_help_ios_wifi03=0x7f020016;
        public static final int car_ic_help_ios_wifi04=0x7f020017;
        public static final int car_ic_help_number01=0x7f020018;
        public static final int car_ic_help_number02=0x7f020019;
        public static final int car_ic_help_number03=0x7f02001a;
        public static final int car_ic_help_number04=0x7f02001b;
        public static final int car_ic_incoming=0x7f02001c;
        public static final int car_ic_loading_1=0x7f02001d;
        public static final int car_ic_loading_2=0x7f02001e;
        public static final int car_ic_loading_logo=0x7f02001f;
        public static final int car_ic_loading_logo_s=0x7f020020;
        public static final int car_ic_more01=0x7f020021;
        public static final int car_ic_qr=0x7f020022;
        public static final int car_ic_usbwifi=0x7f020023;
        public static final int car_qd01=0x7f020024;
        public static final int car_qd02=0x7f020025;
        public static final int car_qd03=0x7f020026;
        public static final int carlife_logo=0x7f020027;
        public static final int com_bg_btn_c_selector=0x7f020028;
        public static final int com_bg_btn_circle=0x7f020029;
        public static final int com_bg_btn_d_selector=0x7f02002a;
        public static final int com_bg_btn_selector=0x7f02002b;
        public static final int com_bg_dialog_item_selector=0x7f02002c;
        public static final int com_bg_foucs=0x7f02002d;
        public static final int com_bg_item_selector=0x7f02002e;
        public static final int com_bottom_bar_connect=0x7f02002f;
        public static final int com_bottom_bar_connect_default=0x7f020030;
        public static final int com_bottom_bar_connect_pressed=0x7f020031;
        public static final int com_bottom_bar_connect_selected=0x7f020032;
        public static final int com_common_bg_card_normal=0x7f020033;
        public static final int com_common_bg_card_normal_night=0x7f020034;
        public static final int com_common_btn_white_normal=0x7f020035;
        public static final int com_common_btn_white_pressed=0x7f020036;
        public static final int com_common_btn_white_selector=0x7f020037;
        public static final int com_diagnose_back_bg_normal=0x7f020038;
        public static final int com_diagnose_back_bg_press=0x7f020039;
        public static final int com_diagnose_back_selector=0x7f02003a;
        public static final int com_dialog_bg=0x7f02003b;
        public static final int com_exitapp_btn_selector=0x7f02003c;
        public static final int com_exitapp_closed=0x7f02003d;
        public static final int com_exitapp_closed_press=0x7f02003e;
        public static final int com_ic_back=0x7f02003f;
        public static final int com_main_fragment_btn_diagnose_default=0x7f020040;
        public static final int com_main_fragment_btn_diagnose_pressed=0x7f020041;
        public static final int com_main_fragment_btn_diagnose_selector=0x7f020042;
        public static final int com_main_fragment_btn_retry_default=0x7f020043;
        public static final int com_main_fragment_btn_retry_pressed=0x7f020044;
        public static final int com_main_fragment_btn_retry_selector=0x7f020045;
        public static final int common_btn_bg_focus=0x7f020046;
        public static final int home_ic_my_setting_help_aoa=0x7f020047;
        public static final int ic_app_logo=0x7f020048;
        public static final int ic_launcher=0x7f020049;
        public static final int ic_launcher_changan=0x7f02004a;
        public static final int ic_phone_call=0x7f02004b;
        public static final int ic_phone_hangup=0x7f02004c;
        public static final int icon_head=0x7f02004d;
        public static final int logo_audi=0x7f02004e;
        public static final int logo_byd=0x7f02004f;
        public static final int logo_cadillac=0x7f020050;
        public static final int logo_changan=0x7f020051;
        public static final int logo_chevrolet=0x7f020052;
        public static final int logo_copyright=0x7f020053;
        public static final int logo_mercedes=0x7f020054;
        public static final int progress_1=0x7f020055;
        public static final int progress_2=0x7f020056;
        public static final int progress_3=0x7f020057;
        public static final int progress_4=0x7f020058;
        public static final int progress_5=0x7f020059;
        public static final int progress_6=0x7f02005a;
        public static final int progress_7=0x7f02005b;
        public static final int progress_8=0x7f02005c;
        public static final int qiya_logo=0x7f02005d;
        public static final int selector_btn_retry=0x7f02005e;
        public static final int shape_btn_normal=0x7f02005f;
        public static final int shape_btn_press=0x7f020060;
        public static final int update_progress_bar=0x7f020061;
        public static final int xiandai_logo=0x7f020062;
    }
    public static final class id {
        public static final int FILL=0x7f0c0000;
        public static final int STROKE=0x7f0c0001;
        public static final int about_tv_version_code=0x7f0c0052;
        public static final int action_settings=0x7f0c007a;
        public static final int android_device=0x7f0c003a;
        public static final int apple_device=0x7f0c003e;
        public static final int arrow1=0x7f0c0057;
        public static final int arrow2=0x7f0c0061;
        public static final int arrow3=0x7f0c0067;
        public static final int arrow4=0x7f0c006e;
        public static final int carlife_msg_text_view=0x7f0c0030;
        public static final int check_content=0x7f0c003c;
        public static final int check_title=0x7f0c003b;
        public static final int common_title_bar=0x7f0c0031;
        public static final int control_btn_back=0x7f0c0015;
        public static final int control_btn_clear=0x7f0c0013;
        public static final int control_btn_delete=0x7f0c0014;
        public static final int control_btn_down=0x7f0c0019;
        public static final int control_btn_home=0x7f0c000c;
        public static final int control_btn_left=0x7f0c0016;
        public static final int control_btn_map=0x7f0c000e;
        public static final int control_btn_media=0x7f0c000f;
        public static final int control_btn_not_support_mic=0x7f0c0026;
        public static final int control_btn_ok=0x7f0c0018;
        public static final int control_btn_phone=0x7f0c000d;
        public static final int control_btn_right=0x7f0c001a;
        public static final int control_btn_seek_add=0x7f0c0012;
        public static final int control_btn_seek_sub=0x7f0c0011;
        public static final int control_btn_selector_next=0x7f0c001c;
        public static final int control_btn_selector_previous=0x7f0c001b;
        public static final int control_btn_up=0x7f0c0017;
        public static final int control_btn_use_mobile_mic=0x7f0c0027;
        public static final int control_car_speed_02=0x7f0c002a;
        public static final int control_car_speed_10=0x7f0c0029;
        public static final int control_music_start=0x7f0c001f;
        public static final int control_music_stop=0x7f0c0020;
        public static final int control_navi_stop=0x7f0c0028;
        public static final int control_phone_call=0x7f0c0021;
        public static final int control_phone_end=0x7f0c0022;
        public static final int control_record_start=0x7f0c001d;
        public static final int control_record_stop=0x7f0c001e;
        public static final int control_video_test_btn1=0x7f0c0024;
        public static final int control_video_test_btn2=0x7f0c0025;
        public static final int control_video_test_et=0x7f0c0023;
        public static final int dialog_carlife_content=0x7f0c002c;
        public static final int dialog_carlife_first_btn=0x7f0c002e;
        public static final int dialog_carlife_second_btn=0x7f0c002f;
        public static final int dialog_carlife_temp=0x7f0c002d;
        public static final int dialog_carlife_title_bar=0x7f0c002b;
        public static final int display_layout=0x7f0c0035;
        public static final int exception_display_img_view=0x7f0c0036;
        public static final int exception_display_text_view=0x7f0c0037;
        public static final int exception_start_app_btn=0x7f0c0038;
        public static final int exit_img_btn=0x7f0c0010;
        public static final int goto_android_layout=0x7f0c0039;
        public static final int goto_apple_layout=0x7f0c003d;
        public static final int guide_viewpager_user_guide=0x7f0c0072;
        public static final int ib_left=0x7f0c0005;
        public static final int ib_right=0x7f0c000a;
        public static final int incall_ib_incoming_answer=0x7f0c0042;
        public static final int incall_ib_incoming_break=0x7f0c0043;
        public static final int incall_ib_offhook_break=0x7f0c0047;
        public static final int incall_layout_incoming=0x7f0c003f;
        public static final int incall_layout_offhook=0x7f0c0044;
        public static final int incall_tv_incoming_desc=0x7f0c0041;
        public static final int incall_tv_incoming_name=0x7f0c0040;
        public static final int incall_tv_offhook_desc=0x7f0c0046;
        public static final int incall_tv_offhook_name=0x7f0c0045;
        public static final int launch_iv_brand_logo=0x7f0c0048;
        public static final int launch_iv_copyright=0x7f0c0049;
        public static final int layout2_l1=0x7f0c005c;
        public static final int layout2_l2=0x7f0c0062;
        public static final int layout3_l1=0x7f0c0069;
        public static final int layout3_l2=0x7f0c006f;
        public static final int layout_l1=0x7f0c0054;
        public static final int layout_l2=0x7f0c0058;
        public static final int ll_title=0x7f0c0007;
        public static final int main_btn_help=0x7f0c004c;
        public static final int main_content_frame=0x7f0c0004;
        public static final int main_img_view=0x7f0c004e;
        public static final int main_info_text_view=0x7f0c004f;
        public static final int main_layout=0x7f0c004a;
        public static final int main_load_round_progress=0x7f0c0051;
        public static final int main_rellayout_status=0x7f0c004d;
        public static final int main_retry_btn=0x7f0c0050;
        public static final int main_root_view=0x7f0c0002;
        public static final int main_video_surface_view=0x7f0c0003;
        public static final int pregress_progress_rate=0x7f0c0077;
        public static final int progress_bar=0x7f0c0076;
        public static final int progress_iv_logo=0x7f0c0075;
        public static final int progress_iv_logo_name=0x7f0c0078;
        public static final int progress_rellayout_loading=0x7f0c0074;
        public static final int rellayout_bar=0x7f0c004b;
        public static final int round_pro_loading_image_view=0x7f0c0073;
        public static final int setting_tv_item_name=0x7f0c0079;
        public static final int tips=0x7f0c0032;
        public static final int tips2=0x7f0c005b;
        public static final int tips2_img=0x7f0c005d;
        public static final int tips2_img2=0x7f0c005f;
        public static final int tips2_img3=0x7f0c0063;
        public static final int tips2_img4=0x7f0c0065;
        public static final int tips2_num=0x7f0c005e;
        public static final int tips2_num2=0x7f0c0060;
        public static final int tips2_num3=0x7f0c0064;
        public static final int tips2_num4=0x7f0c0066;
        public static final int tips3=0x7f0c0068;
        public static final int tips3_img=0x7f0c006a;
        public static final int tips3_img2=0x7f0c006c;
        public static final int tips3_img3=0x7f0c0070;
        public static final int tips3_num=0x7f0c006b;
        public static final int tips3_num2=0x7f0c006d;
        public static final int tips3_num3=0x7f0c0071;
        public static final int tips_img=0x7f0c0033;
        public static final int tips_img2=0x7f0c0055;
        public static final int tips_img3=0x7f0c0059;
        public static final int tips_num=0x7f0c0034;
        public static final int tips_num2=0x7f0c0056;
        public static final int tips_num3=0x7f0c005a;
        public static final int touch_view=0x7f0c0053;
        public static final int tv_right=0x7f0c000b;
        public static final int tv_title=0x7f0c0006;
        public static final int tv_title_desc=0x7f0c0009;
        public static final int view_hide=0x7f0c0008;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int carlife_common_title_bar_new=0x7f030001;
        public static final int control_test_window=0x7f030002;
        public static final int dialog_carlife=0x7f030003;
        public static final int dialog_carlife_message=0x7f030004;
        public static final int frag_authorization_request_help=0x7f030005;
        public static final int frag_exception=0x7f030006;
        public static final int frag_help_android=0x7f030007;
        public static final int frag_help_apple=0x7f030008;
        public static final int frag_help_main=0x7f030009;
        public static final int frag_incall=0x7f03000a;
        public static final int frag_launch=0x7f03000b;
        public static final int frag_main=0x7f03000c;
        public static final int frag_ncm_help=0x7f03000d;
        public static final int frag_setting=0x7f03000e;
        public static final int frag_setting_about=0x7f03000f;
        public static final int frag_touch=0x7f030010;
        public static final int frag_usb_help=0x7f030011;
        public static final int frag_wifi_help=0x7f030012;
        public static final int fragment_user_guide=0x7f030013;
        public static final int layout_carlife_round_progress=0x7f030014;
        public static final int layout_progress_bar=0x7f030015;
        public static final int list_item_setting=0x7f030016;
    }
    public static final class menu {
        public static final int main=0x7f0b0000;
    }
    public static final class string {
        public static final int accepting_calling=0x7f070037;
        public static final int action_settings=0x7f070000;
        public static final int alert_cancel=0x7f070001;
        public static final int alert_confirm=0x7f070002;
        public static final int alert_notification=0x7f070003;
        public static final int alert_quit=0x7f070004;
        public static final int alert_quit_app_content=0x7f070005;
        public static final int answer_call=0x7f070038;
        public static final int app_name=0x7f070006;
        public static final int auth_tips=0x7f070039;
        public static final int auth_tips_img=0x7f07003a;
        public static final int auth_tips_tv_title=0x7f07003b;
        public static final int baidu_help=0x7f07003c;
        public static final int baidu_logo=0x7f070007;
        public static final int carlife_phone_not_support_hint=0x7f07003d;
        public static final int carlife_toast_crash=0x7f07003e;
        public static final int carlife_toast_gps_open=0x7f07003f;
        public static final int carlife_toast_protocol_not_match=0x7f070040;
        public static final int carlife_update_backstage=0x7f070008;
        public static final int carlife_update_cancel=0x7f070009;
        public static final int carlife_update_click_to_install=0x7f07000a;
        public static final int carlife_update_download_fail=0x7f07000b;
        public static final int carlife_update_download_failed_dialog_content=0x7f07000c;
        public static final int carlife_update_download_failed_dialog_retry=0x7f07000d;
        public static final int carlife_update_download_failed_dialog_title=0x7f07000e;
        public static final int carlife_update_download_finish=0x7f07000f;
        public static final int carlife_update_downloading=0x7f070010;
        public static final int carlife_update_go_to_foreground=0x7f070011;
        public static final int carlife_update_no_network=0x7f070012;
        public static final int carlife_update_no_new_version=0x7f070013;
        public static final int carlife_update_tips_dialog_cancel=0x7f070014;
        public static final int carlife_update_tips_dialog_confirm=0x7f070015;
        public static final int carlife_update_tips_dialog_title=0x7f070016;
        public static final int carlife_update_wait_for_complete=0x7f070017;
        public static final int carlife_video_permission_denied_hint=0x7f070041;
        public static final int carlife_video_permission_hint=0x7f070042;
        public static final int check_update=0x7f070018;
        public static final int conf_init_fail=0x7f070043;
        public static final int connect_background_hint=0x7f070019;
        public static final int connect_diagnose_title=0x7f07001a;
        public static final int connect_exit_carlife=0x7f07001b;
        public static final int connect_progress_number=0x7f07001c;
        public static final int connect_screenoff_hint=0x7f07001d;
        public static final int connect_start_carlife=0x7f07001e;
        public static final int control_add=0x7f070044;
        public static final int control_answer_call=0x7f070045;
        public static final int control_back=0x7f070046;
        public static final int control_car_speed_02=0x7f070047;
        public static final int control_car_speed_10=0x7f070048;
        public static final int control_clear=0x7f070049;
        public static final int control_commit=0x7f07004a;
        public static final int control_delete=0x7f07004b;
        public static final int control_down=0x7f07004c;
        public static final int control_home=0x7f07004d;
        public static final int control_left=0x7f07004e;
        public static final int control_map=0x7f07004f;
        public static final int control_media=0x7f070050;
        public static final int control_mobile_mic=0x7f070051;
        public static final int control_music_start=0x7f070052;
        public static final int control_music_stop=0x7f070053;
        public static final int control_navi_stop=0x7f070054;
        public static final int control_next=0x7f070055;
        public static final int control_no_mic=0x7f070056;
        public static final int control_ok=0x7f070057;
        public static final int control_phone=0x7f070058;
        public static final int control_phone_call=0x7f070059;
        public static final int control_phone_end=0x7f07005a;
        public static final int control_previous=0x7f07005b;
        public static final int control_record_start=0x7f07005c;
        public static final int control_record_stop=0x7f07005d;
        public static final int control_right=0x7f07005e;
        public static final int control_save_spspps=0x7f07005f;
        public static final int control_start_call=0x7f070060;
        public static final int control_sub=0x7f070061;
        public static final int control_up=0x7f070062;
        public static final int download_carlife=0x7f07001f;
        public static final int gps_data_tips=0x7f070063;
        public static final int help_android_aoa_device=0x7f070064;
        public static final int help_android_aoa_title=0x7f070065;
        public static final int help_android_check_content=0x7f070066;
        public static final int help_android_check_title=0x7f070067;
        public static final int help_android_device=0x7f070068;
        public static final int help_android_reboot_and_try=0x7f070069;
        public static final int help_android_usb_title=0x7f07006a;
        public static final int help_apple_device=0x7f07006b;
        public static final int help_apple_ncm_devices=0x7f07006c;
        public static final int help_apple_ncm_title=0x7f07006d;
        public static final int help_apple_reboot_and_try=0x7f07006e;
        public static final int help_apple_title=0x7f07006f;
        public static final int help_main_android_device=0x7f070070;
        public static final int help_main_apple_device=0x7f070071;
        public static final int help_main_phone_system=0x7f070072;
        public static final int help_main_title=0x7f070073;
        public static final int incoming_calling=0x7f070074;
        public static final int line_is_busy=0x7f070075;
        public static final int line_is_coming=0x7f070076;
        public static final int loading_progress_tips=0x7f070077;
        public static final int module_custom_usb_ConnectType=0x7f070020;
        public static final int module_custom_wifi_ConnectType=0x7f070021;
        public static final int module_custom_wifi_default_ip=0x7f070022;
        public static final int module_setting=0x7f070023;
        public static final int ncm_request_title=0x7f070078;
        public static final int ncm_tips=0x7f070079;
        public static final int ncm_tips_img=0x7f07007a;
        public static final int notification_download_title=0x7f07007b;
        public static final int pcm_recorder_error=0x7f07007c;
        public static final int pcm_recorder_wrong=0x7f07007d;
        public static final int phone_name_unknown=0x7f07007e;
        public static final int phone_state_calling=0x7f07007f;
        public static final int phone_state_incoming=0x7f070080;
        public static final int progress_bar_rate=0x7f070081;
        public static final int reject_call=0x7f070082;
        public static final int title_activity_base=0x7f070024;
        public static final int usb_cable_connected=0x7f070025;
        public static final int usb_cable_disconnected=0x7f070026;
        public static final int usb_connect_adb_notopen_aoa_notsupport=0x7f070083;
        public static final int usb_connect_aoa_accessory_mode=0x7f070084;
        public static final int usb_connect_aoa_change_adb=0x7f070085;
        public static final int usb_connect_aoa_no_permission=0x7f070086;
        public static final int usb_connect_aoa_not_support=0x7f070087;
        public static final int usb_connect_aoa_request_md_permisson=0x7f070088;
        public static final int usb_connect_btn_retry=0x7f070027;
        public static final int usb_connect_btn_retry_info=0x7f070028;
        public static final int usb_connect_fail=0x7f070029;
        public static final int usb_connect_fail_install=0x7f07002a;
        public static final int usb_connect_fail_not_surpport=0x7f07002b;
        public static final int usb_connect_fail_not_surpport2=0x7f070089;
        public static final int usb_connect_fail_start=0x7f07002c;
        public static final int usb_connect_fail_start_bdsc=0x7f07002d;
        public static final int usb_connect_fail_timeout=0x7f07002e;
        public static final int usb_connected_hold=0x7f07002f;
        public static final int usb_connecting=0x7f070030;
        public static final int usb_connecting_hold_auto=0x7f070031;
        public static final int usb_connecting_hold_unauto=0x7f070032;
        public static final int usb_help_tips=0x7f07008a;
        public static final int usb_help_tips2=0x7f07008b;
        public static final int usb_help_tips2_img=0x7f07008c;
        public static final int usb_help_tips2_img2=0x7f07008d;
        public static final int usb_help_tips2_img3=0x7f07008e;
        public static final int usb_help_tips2_img4=0x7f07008f;
        public static final int usb_help_tips3=0x7f070090;
        public static final int usb_help_tips3_img=0x7f070091;
        public static final int usb_help_tips3_img2=0x7f070092;
        public static final int usb_help_tips3_img3=0x7f070093;
        public static final int usb_help_tips_img=0x7f070094;
        public static final int usb_help_tips_img2=0x7f070095;
        public static final int usb_help_tips_img3=0x7f070096;
        public static final int usb_help_title=0x7f070097;
        public static final int usb_not_connected=0x7f070098;
        public static final int usb_statusbar_connected=0x7f070033;
        public static final int usb_statusbar_connecting=0x7f070034;
        public static final int usb_statusbar_disconnected=0x7f070035;
        public static final int usb_statusbar_title=0x7f070036;
        public static final int usb_switched=0x7f070099;
        public static final int version_code_prefix=0x7f07009a;
        public static final int video_give_permissions=0x7f07009b;
        public static final int video_not_supported=0x7f07009c;
        public static final int wifi_help_tips2=0x7f07009d;
        public static final int wifi_help_tips2_img=0x7f07009e;
        public static final int wifi_help_tips2_img2=0x7f07009f;
        public static final int wifi_help_tips2_img3=0x7f0700a0;
        public static final int wifi_help_tips2_img4=0x7f0700a1;
        public static final int wifi_help_title=0x7f0700a2;
        public static final int wifi_switched=0x7f0700a3;
    }
    public static final class style {
        /**  API 11 theme customizations can go here. 
 API 14 theme customizations can go here. 

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.















        
         */
        public static final int AppBaseTheme=0x7f090000;
        /**  All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f090001;
        public static final int CarlifeDialog=0x7f090002;
        public static final int CarlifeRoundProgress=0x7f090003;
        public static final int CustomTheme=0x7f090004;
    }
    public static final class xml {
        public static final int device_filter=0x7f050000;
    }
    public static final class styleable {
        /** Attributes that can be used with a RoundProgressBar.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #RoundProgressBar_max com.baidu.carlifevehicle:max}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundProgressBar_roundColor com.baidu.carlifevehicle:roundColor}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundProgressBar_roundProgressColor com.baidu.carlifevehicle:roundProgressColor}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundProgressBar_roundWidth com.baidu.carlifevehicle:roundWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundProgressBar_style com.baidu.carlifevehicle:style}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundProgressBar_textColor com.baidu.carlifevehicle:textColor}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundProgressBar_textIsDisplayable com.baidu.carlifevehicle:textIsDisplayable}</code></td><td></td></tr>
           <tr><td><code>{@link #RoundProgressBar_textSize com.baidu.carlifevehicle:textSize}</code></td><td></td></tr>
           </table>
           @see #RoundProgressBar_max
           @see #RoundProgressBar_roundColor
           @see #RoundProgressBar_roundProgressColor
           @see #RoundProgressBar_roundWidth
           @see #RoundProgressBar_style
           @see #RoundProgressBar_textColor
           @see #RoundProgressBar_textIsDisplayable
           @see #RoundProgressBar_textSize
         */
        public static final int[] RoundProgressBar = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007
        };
        /**
          <p>This symbol is the offset where the {@link com.baidu.carlifevehicle.R.attr#max}
          attribute's value can be found in the {@link #RoundProgressBar} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.baidu.carlifevehicle:max
        */
        public static final int RoundProgressBar_max = 5;
        /**
          <p>This symbol is the offset where the {@link com.baidu.carlifevehicle.R.attr#roundColor}
          attribute's value can be found in the {@link #RoundProgressBar} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.baidu.carlifevehicle:roundColor
        */
        public static final int RoundProgressBar_roundColor = 0;
        /**
          <p>This symbol is the offset where the {@link com.baidu.carlifevehicle.R.attr#roundProgressColor}
          attribute's value can be found in the {@link #RoundProgressBar} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.baidu.carlifevehicle:roundProgressColor
        */
        public static final int RoundProgressBar_roundProgressColor = 1;
        /**
          <p>This symbol is the offset where the {@link com.baidu.carlifevehicle.R.attr#roundWidth}
          attribute's value can be found in the {@link #RoundProgressBar} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.baidu.carlifevehicle:roundWidth
        */
        public static final int RoundProgressBar_roundWidth = 2;
        /**
          <p>This symbol is the offset where the {@link com.baidu.carlifevehicle.R.attr#style}
          attribute's value can be found in the {@link #RoundProgressBar} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>STROKE</code></td><td>0</td><td></td></tr>
<tr><td><code>FILL</code></td><td>1</td><td></td></tr>
</table>
          @attr name com.baidu.carlifevehicle:style
        */
        public static final int RoundProgressBar_style = 7;
        /**
          <p>This symbol is the offset where the {@link com.baidu.carlifevehicle.R.attr#textColor}
          attribute's value can be found in the {@link #RoundProgressBar} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.baidu.carlifevehicle:textColor
        */
        public static final int RoundProgressBar_textColor = 3;
        /**
          <p>This symbol is the offset where the {@link com.baidu.carlifevehicle.R.attr#textIsDisplayable}
          attribute's value can be found in the {@link #RoundProgressBar} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.baidu.carlifevehicle:textIsDisplayable
        */
        public static final int RoundProgressBar_textIsDisplayable = 6;
        /**
          <p>This symbol is the offset where the {@link com.baidu.carlifevehicle.R.attr#textSize}
          attribute's value can be found in the {@link #RoundProgressBar} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.baidu.carlifevehicle:textSize
        */
        public static final int RoundProgressBar_textSize = 4;
    };
}
